package com.deepika.multi_choice_list_add_function_testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestPOJO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestPOJO() {
    }




}